### PR TITLE
fix: typo UnataggedSign1Message -> UntaggedSign1Message

### PR DESCRIPTION
**Pull request by spennymac**
Small change to fix the typo.

### CODE REVIEW

**Comment by spennymac** [comment]
Issue: https://github.com/veraison/go-cose/issues/149

**Review by setrofim — APPROVED** [review]
LGTM!

**Comment by spennymac** [comment]
Need one more reviewer :)

**Review by qmuntal — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!
Thanks for spotting this

**Pull request merged**
