### PR TITLE
Upload the Trail of Bits public security assessment report

### PR DESCRIPTION
**Pull request by ESultanik**
Adds a copy of the public report published at https://github.com/trailofbits/publications/blob/master/reviews/Microsoft-go-cose.pdf

### CODE REVIEW

**Review by qmuntal — APPROVED** [review]
Great!

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Comment by SteveLasker** [comment]
Thanks @ESultanik,
The report looks great, and appreciate the links in the doc to the mitigated high and low issues that were identified.
One minor formating, ownership request:
While Microsoft commissioned the report and is supporting the veraison project, the report should reflect the veraison/go-cose project maintainers to properly give credit to the folks at ARM that initiated the effort. 

Page 11
s/go-cose: Microsoft’s COSE implementation in Go.
r/The veraison project, go-cose implementation in Go.

Page 19
s/The Microsoft go-cose library is a work in progress with continuous development. Trail of Bits recommends that Microsoft address the findings detailed in this report and take the following additional steps prior to deployment:

r/The veraison/go-cose library is a work in progress with continuous development. Trail of Bits recommends the veraison project address the findings detailed in this report and take the following additional steps prior to deployment:

**Comment by ESultanik** [comment]
No problem, we will update the report and tag you here when it's ready.

**Comment by ESultanik** [comment]
I just pushed an updated version of the report. I didn't rebase this branch, so the old version is still in the git history. Let me know if you'd rather I do a rebase.

**Review by SteveLasker — APPROVED** [review]
Thanks, @ESultanik for the updates and to the Trail of Bits team for the thorough review.

**Pull request merged**
