### PR TITLE
Refactor Key to support custom parameters

### PR DESCRIPTION
**Pull request by qmuntal**
This PR redesigns `Key` so all non-common parameters are stored in a map instead, even the ones from known key types (i.e. EC2, OKP, and Symmetric keys). This allows `go-cose` to support key types and parameters that are not defined in RFC8152 without having to break the module API. See #151 for more context.

The Key struct now looks like this:

```go
type Key struct {
        // Common Params
	KeyType KeyType
	KeyID []byte
	Algorithm Algorithm
	KeyOps []KeyOp
	BaseIV []byte

        // Custom Params
	Params map[interface{}]interface{}
}
```

I've also added some helper functions to access the known and unknown key parameters:

```go
// Useful to retrieve all parameters relevant for each known key type
func (*Key) OKP() (crv Curve, x []byte, d []byte)
func (*Key) EC2() (crv Curve, x []byte, y, d []byte)
func (*Key) Symmetric() (k []byte)

// Useful to retrieve individual parameters
func (*Key) ParamBytes(label interface{}) ([]byte, bool)
func (*Key) ParamInt(label interface{}) (int64, bool)
func (*Key) ParamUint(label interface{}) (uint64, bool)
func (*Key) ParamString(label interface{}) (string, bool)
func (*Key) ParamBool(label interface{}) (bool, bool)
```

A good amount of new test cases have been added.

@setrofim I've remove the `intOrStr` struct, as it is not necessary with the new way of decoding keys, It is a pity, because I conceptually liked it. If we ever release a new major version, we should consider using something like that to have a better type enforcement in all map labels.

### CODE REVIEW

**Review by setrofim — APPROVED** [review]
LGTM!

**Review by thomas-fossati — APPROVED** [review]
good stuff 👍

**Comment by qmuntal** [comment]
@thomas-fossati @setrofim I've added one last commit to this PR, in case you want to take another look.

**Comment by thomas-fossati** [comment]
> @thomas-fossati @setrofim I've added one last commit to this PR, in case you want to take another look.

neat!

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Pull request merged**
