### PR TITLE
chore: go fmt

### PR DESCRIPTION
**Pull request by alex-richards**
Reformatted with `go fmt`. `bench_test.go` was CRLF formatted.

### CODE REVIEW

**Review by thomas-fossati — APPROVED** [review]
thank you!

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by SteveLasker** [comment]
This has been tagged for the next v1.4.0 release. If folks feel this should be in v1.3], please indicate it here.

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
I would object to putting this in 1.3, leave it in 1.4

**Comment by SteveLasker** [comment]
Merging, with the intent to release in 1.4 as 1.3 is ready for release.

**Pull request merged**
