### PR TITLE
Use curve modulo instead of field size to calculate ECDSA signature length

### LINKED ISSUE #59: Field/order size confusion in ECDSA signature length
In ecdsa.go, lines [99](https://github.com/veraison/go-cose/blob/8cef769ef52c8fc111a8b1e4da83649f1cb170d0/ecdsa.go#L99) and [113](https://github.com/veraison/go-cose/blob/8cef769ef52c8fc111a8b1e4da83649f1cb170d0/ecdsa.go#L113), the expected length of an ECDSA signature is computed from `curve.Params().BitSize`, which is the size (in bits) of the field in which the point coordinates are expressed (so says [the Go documentation](https://pkg.go.dev/crypto/elliptic@go1.18.1#CurveParams), at least). However, an ECDSA signature is a pair (_r_,_s_) of integers modulo _n_, where _n_ is the order of the subgroup generated by the base point; thus, the size of _n_ should normally be used to infer the signature size, not the size of the field. Depending on the curve, the field size may be arbitrarily greater than the subgroup order; it may also be smaller by 1 bit (and in that case, using the field size for the encoded signature length may lead to value truncation or errors).

RFC 8152 is rather unhelpful here because it just says (section 8.1) that one should use the "key size", through some variable denoted "key_length", neither of which being properly defined. For the three usual NIST curves (P-256, P-384 and P-521), the field size and the subgroup order size happen to be identical, making the point a bit moot. However, `go-cose` inherently supports all curves that can fit in the Go API, and that is very open-ended and may include curves where the field and the order sizes do not match, even after rounding to a length in bytes. In all generality, using the order length is "more correct" than using the field size (and also more in line with pre-existing standards using ECDSA).

I suggest changing these two expressions into `curve.Params().N.BitLen()`, which would use the order length systematically.

### PR DESCRIPTION
**Pull request by qmuntal**
Fixes #59

@SteveLasker @shizhMSFT

### CODE REVIEW

**Comment by SteveLasker** [comment]
@sylvanc, can you also please provide some 👀's

**Review by thomas-fossati — APPROVED** [review]
LGTM

**Review by yogeshbdeshpande — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]

**Comment by SteveLasker** [comment]
Thanks @qmuntal, @jaredpar, @yogeshbdeshpande 
@pornin, do you mind taking a look to confirm it meets your goals for #59?

**Comment by pornin** [comment]
The change to `ecdsa.go` is exactly what I had in mind.

**Comment by SteveLasker** [comment]
Thanks @pornin, awesome work @qmuntal

**Pull request merged**
